/**
 * Itinerary — renders a generated trip as a structured, readable
 * day-by-day plan (never a wall of chat text).
 *
 * Hierarchy: Itinerary → DayCard → TimeBlock.
 */

const TIME_ICONS = {
  Morning: (
    <path d="M12 16a4 4 0 018 0M16 9v2.2M8.6 11l1.5 1.6M23.4 11l-1.5 1.6M6 19.5h20" transform="translate(-4 -4)" />
  ),
  Afternoon: (
    <>
      <circle cx="12" cy="12" r="4" />
      <path d="M12 3.5v2M12 18.5v2M3.5 12h2M18.5 12h2M6 6l1.4 1.4M16.6 16.6L18 18M18 6l-1.4 1.4M7.4 16.6L6 18" />
    </>
  ),
  Evening: <path d="M19.5 13.5A7.5 7.5 0 1110.5 4.5a6 6 0 009 9z" />,
};

function TimeBlock({ block }) {
  return (
    <div className="time-block">
      <div className="time-block-label">
        <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" aria-hidden="true">
          {TIME_ICONS[block.time]}
        </svg>
        <span>{block.time}</span>
      </div>
      <div className="time-block-body">
        <h4>{block.title}</h4>
        <p>{block.description}</p>
        {(block.duration || block.category) && (
          <p className="time-block-meta">
            {[block.category, block.duration].filter(Boolean).join(' · ')}
          </p>
        )}
      </div>
    </div>
  );
}

function DayCard({ day }) {
  return (
    <article className="day-card panel">
      <header className="day-card-head">
        <span className="day-card-num" aria-hidden="true">
          {String(day.day).padStart(2, '0')}
        </span>
        <div>
          <p className="day-card-kicker">Day {day.day}</p>
          <h3>{day.theme}</h3>
        </div>
      </header>
      <div className="day-card-blocks">
        {day.blocks.map((block) => (
          <TimeBlock key={block.time} block={block} />
        ))}
      </div>
    </article>
  );
}

export default function Itinerary({ itinerary }) {
  return (
    <section className="itinerary" aria-label="Your generated itinerary">
      <header className="itinerary-head">
        <p className="eyebrow">Your plan</p>
        <h2>{itinerary.title}</h2>
        {itinerary.summary && <p className="lede">{itinerary.summary}</p>}
        <p className={`itinerary-source ${itinerary.source === 'gemini' ? 'is-ai' : ''}`}>
          {itinerary.source === 'gemini'
            ? 'Generated by Google Gemini'
            : 'Sample plan from the Wanderly guide (offline mode)'}
        </p>
      </header>
      <div className="itinerary-days">
        {itinerary.days.map((day) => (
          <DayCard key={day.day} day={day} />
        ))}
      </div>
    </section>
  );
}
